### PR TITLE
couple of minor changes

### PR DESCRIPTION
**Pull request by SaqibS**
- Deleted Nuget files from ImportExport as these projects now pull from the common repository.
- Checked in my VSExpress solution which I've been using (choose not to instal big VS on laptop).

### CODE REVIEW

**Comment by alastairs** [comment]
Nice one Saqib, I was just about to start looking at that packages directory myself!

**Comment by alastairs** [comment]
Before this pull request is merged in, the repositories.config file in the top-level packages directory will need to be modified to include the following two lines:

```
<repository path="..\GiveCRM.ImportExport\GiveCRM.ImportExport\packages.config" />
<repository path="..\GiveCRM.ImportExport\GiveCRM.ImportExport.Test\packages.config" />
```

The commit deletes the repositories.config file in which they were originally listed, and does not move them.

**Comment by SaqibS** [comment]
My version of src/packages/repositories.config contains both those lines, 
and my head is clean (or whatever the git lingo is).

-----Original Message-----

**Comment by alastairs** [comment]
My mistake - looks like they're already in there on master.

**Pull request merged**
