### PR TITLE
logging

### PR DESCRIPTION
**Pull request by kuangmarkeleven**
Logging is now done by Elmah, ASP.NET health monitoring and a bespoke logging class (which is a simple wrapper around log4net). Logging now goes to a seperate db GiveCRMLogging for which there is a new DB project. If a new DB isn't required it'll be easy enough to pop the required tables and stored procs into the admin DB and swap around some connection strings in web.config.

Config in web.config points Elmah to log in the DB, the <healthMonitoring> section configures ASP.NET health monitoring and the <log4net> section likewise configures log4net, it's here that different levels of logging and be enabled/disabled for the LogService behind ILogService. I've not written any tests because it's mostly config and the ILogService implementation is a very very thin facade over log4net's own calls.

### CODE REVIEW

**Comment by alastairs** [comment]
Hi Carl

There is a Facade over log4net provided by Ninject.Extensions.Logging, which should be in the repository already (although possibly only in the branch that I emailed you details of).  I'd prefer we made use of that Ninject Extension rather than a bespoke implementation.  

I'm ok with the logging data being written to a separate DB (keeps the load down on the data DB), provided there is a logging DB associated with each instance of GiveCRM when deployed.  That's a consideration for a later date, though, I think.

Cheers

Alastair

**Comment by kuangmarkeleven** [comment]
Hi Alistair,

I'll take a look at the Ninject logging extension, do you happen to
have a like to some reasonable documentation on it and it's usage as
google doesn't seem to find me any at the moment

thanks

Carl

On 9 January 2012 14:54, Alastair Smith
reply@reply.github.com
wrote:

**Comment by alastairs** [comment]
Hi Carl

No, I haven't found any documentation, but it seems to be fairly simple from my own investigations: you pull in the extension via NuGet and program against the Ninject.Extensions.Logging.ILogger interface.  You also need to pull in the Ninject.Extensions.Logging.log4net package (or NLog if you prefer).  I think GiveCRM should be sufficiently configured to pull in log4net and wire it up correctly at runtime, but log4net's configuration will need to be implemented as appropriate.  

I've got some changes in [this branch](https://github.com/alastairs/GiveCRM/tree/log4net) which you may find helpful.

Alastair

**Comment by alastairs** [comment]
Re: documentation of the logging extension, there isn't that much available.  I have come across these two items, though:
- https://github.com/ninject/ninject.extensions.logging/wiki/Using
- http://groups.google.com/group/ninject/browse_thread/thread/13f6d3787bfd6b77?pli=1 (May be of limited use...)
- [A tutorial of sorts](http://blog.tonysneed.com/2011/10/09/using-nlog-with-dependency-injection/) using NLog rather than log4net.

Hope that helps!

Alastair

**Comment by kuangmarkeleven** [comment]
Hi Alastair,

I'm going to expand my logging facade interface a little to to cover
the ILogging interface but essentially I think what I've provided is a
better solution than simply relying on the DI containers built in
logging provided by the extension primarily because if for some reason
the project to decides not to use Ninject you've lost your logging.
I've simply provided a service implementing the ILogging interface
that is log4net underneath which itself is registered with the DI
container. However, using this it could just as easily be castle or
unity rather than ninject. Like I say, I'll expand the interface a
little more so that the exception itself can recorded. Let me know
what you think

Carl

On 7 February 2012 22:48, Alastair Smith
reply@reply.github.com
wrote:

**Comment by alastairs** [comment]
Hi Carl

Thanks for taking another look at this, much appreciated.

Your suggestion sounds sensible; I hadn't really considered that
aspect of the logging extension.

It would be useful to be able to reuse the logging abstraction if
possible. The Data Generator has some half-complete work in progress
to add logging to it (albeit to screen rather than to file), and we
will want logging capabilities in the various responsibilities of
GiveCRM.Admin as well.

Send through an updated pull request when you're done and we'll take
it from there.

Cheers

Alastair

Sent from my iPad

On 12 Feb 2012, at 22:22, Carl Griffiths
reply@reply.github.com
wrote:

**Comment by kuangmarkeleven** [comment]
ok. I'll create a new project in the GiveCRM Solution called Shared
Services and move the logging to there. Then it can be referenced from
the givecrm site, the data export and the admin. I'll do that tonight
and put forward a new pull request.

On 12 February 2012 23:14, Alastair Smith
reply@reply.github.com
wrote:

**Pull request closed without merging**
