### PR TITLE
Part fix to issue #79

### PR DESCRIPTION
**Pull request by adrianbanks**
Made the importer auto-detect the version of excel based on the file extension of the import file. There is still an assumption that the import data is on the first worksheet in the file, but I haven't changed that as I think it requires further thought before going further.

### CODE REVIEW

**Comment by alastairs** [comment]
This looks like a nice change. It would be nice if the `ExcelFileType` enum wasn't leaked out of the business logic layer (why should the `ExcelImportController` have to care what format the file is in?) but I don't currently see a good refactoring that will improve the situation without coupling the Excel library to a `FileStream`.

**Comment by adrianbanks** [comment]
Yes, I had a similar thought. It was either give the responsibility of figuring out which version of Excel the import file was for to the `ExcelImportService` of the `ExcelImportController`. It would make more sense for the import service to do it, but that would require passing a filename to it which would not be used for anything else. I chose this was as it was a bit nicer, even though the `ExcelFileType` is now used in the Web layer.

**Comment by alastairs** [comment]
Think I'm going to have a peek around under the covers of the Excel library: it would be nice if it could just work out from the input Stream what format the file is in...

**Comment by alastairs** [comment]
Some conversations with Adrian indicate that the version of Excel from the Stream as the Stream must be reversible in order to work this out, and in order for the Stream to be reversible, it must be a FileStream.  There may be another way around this which I'll investigate when I have a moment, but in the meantime this seems like a good change to make.

**Pull request merged**
