### PR TITLE
Cleanup of the Donations contoller - removed the DB dependency for testability

### PR DESCRIPTION
**Pull request by stack72**
removed the dependency of the DonationsDb from the Donations controller - this is now in a Donations ServiceLayer class

### CODE REVIEW

**Comment by kendallmiller** [comment]
Reviewed and agreed.  Good refinement.  We should consider how we expand from here to an IoC module approach.

**Comment by stack72** [comment]
there is already an IoC container in place - Ninject is already there and was being used by the Campaign Controller before I added anything to the project! 

I was going to suggest AutoFac but someone has beaten me to an IoC approach!

**Comment by alastairs** [comment]
Yeah, I wired in Ninject with @nbarnwell over the weekend for its superior MVC support.

**Comment by stack72** [comment]
I'd argue superior :) 

But Im very glad a simple IoC container was chosen! Nice work guys!

**Comment by alastairs** [comment]
Hah! Yeah, I think Mark Rendle mentioned AutoFac as being better too, but then pointed out the speed concerns with Ninject were basically a non-issue.  If AutoFac (or some other library) is demonstrably better than Ninject _and works as well with MVC_ as Ninject, I'm happy to swap it out at this stage whilst there's not much stuff depending on it.

**Comment by stack72** [comment]
The only issue with Ninject is that you have to have the Ninject MVC code in AppCode and this is "messy". If you dont want to have that then the Global has to inherit from NinjectApplication - which I hate

To be honest its a non issue - we have 1 in place now so I'm happy :)

**Comment by nbarnwell** [comment]
I quite like the Ninject stuff, but Windsor has much more flexibility I think with installers etc. I'm going to investigate MVCcontrib to see if I can put Winsor back in (had to remove it because even after I wired up my WindsorControllerFactory, there was a problem with non-controllers being found). If I get it to work in one of my hobby projects I'll propose it to the group and pop Windsor back in.

**Comment by alastairs** [comment]
Do Ninject modules not serve the same purpose as Windsor installers? What flexibility do they lack that Windsor provides?

**Comment by nbarnwell** [comment]
Lol you didn't tell us about those yesterday! Since it's working right now,
there's more important things to do anyway. There are other things I like
about Windsor, but if Ninject meets those requirements too then there's no
reason to ever swap.

Neil Barnwell.
_Twitter:_ @nbarnwell
_e-mail:_ mailbox@neilbarnwell.co.uk
_web:_ http://www.neilbarnwell.co.uk

**Comment by alastairs** [comment]
Ah, must have been Robin I was having that discussion with then!

**Comment by chrisjdiver** [comment]
I did an eval on IoC containers and we went for AutoFac in the end, there are some blog posts about performance in which it does very well and it's incredibly easy to use. Worth checking out if you haven't used it. 

If Ninject is set up and meets the requirements then I don't think it's worth splitting hairs about. If it doesn't meet the requirements then i'd suggest AutoFac as an alternative.

**Comment by kendallmiller** [comment]
I'm fine with us changing one but I think we want to have this be a "settled" part of the architecture four our next set of work.  If we want to change, someone who's ready to rock with AutoFac should do it as a single merge so we can verify it and cut over, then move forwards.  What we need is a voting system :)

**Comment by stack72** [comment]
I think we are fine with Ninject to be honest- there will be no real difference as long as we dont hack the IoC container to pieces :)

I personally think its decision made - Ninject is there and will continue!

**Pull request merged**
