### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by kuangmarkeleven**
Logging service moved to own project and out of givecrm.web
Logging in web project via Elmah, ILogService (facade over log4net) and MC health monitoring to seperate givecrm logging db

### CODE REVIEW

**Comment by alastairs** [comment]
Hi Carl

The pull request appears to be missing the new LoggingService project (and possibly some other changes too).  The pull request thinks your last commit was 2 months ago.  Please could you update it with your latest changes?

Cheers

Alastair

**Comment by kuangmarkeleven** [comment]
I'll look into it this evening though I suspect that my familiarity
with mercurial has made me forget that I need to explicitly add files
with git

Sent from my Windows Phone

**Comment by kuangmarkeleven** [comment]
updated now, should contain all the changes sorry about that

**Comment by alastairs** [comment]
Thanks for the update, it looks more complete now.  However, it looks like you're missing some of the changes made on master since you created your fork: notably, the move of the ImportExport projects doesn't seem to be in your fork.  Please could you pull in the changes from the main repository and update the pull request.  

Sorry to keep throwing hoops at you to jump through; I think this should be the last one!

**Comment by kuangmarkeleven** [comment]
i must admit I'm at a loss then, I've done a fetch and also a pull
from givecrm master and then a merge into my master already. If I do
it again it says it's all up to date with nothing to do. I'll have to
go read some git docs to see if I can figure out what's going on.

On 14 February 2012 19:47, Alastair Smith
reply@reply.github.com
wrote:

**Comment by alastairs** [comment]
Oh dear... I'll take a closer look at the graph and see what's happened.

**Comment by alastairs** [comment]
Ok, I've compared it with the main GiveCRM repo (rather than my own fork...) and things work much more nicely.  Looks like everything works ok, except I can't find any usages of the ILogService interface's methods at all.  GiveCRM.Web.Controllers.CampaignController holds a reference to an ILogService, but doesn't do anything with it.  Is that as you expect?

**Comment by kuangmarkeleven** [comment]
Hi Alistair, yes I've implemented the service and made sure it injects
ok but I've nit used ut anywhere as I've no real idea of what is mature
enough to not be changing yet. I'll look at the trello board later and
try to get a view over what's what and go from there putting in the
logging if needed. Would be a good idea to have some guidelines to
logging usage though, for example expectations of logging for the
different logging levels i.e. when people should or shouldn't log info.
Thanks, Carl

Sent from my Windows Phone

**Pull request merged**
