### PR TITLE
Addition of a Class Library to test the web layer of GiveCRM

### PR DESCRIPTION
**Pull request by stack72**

### CODE REVIEW

**Comment by alastairs** [comment]
I noticed the new test project is using RhinoMocks; Moq should be wired in to some projects already so it might be best to stick with that.  

If Moq is not in this repository already, it will be once my own pull request is merged.

**Comment by stack72** [comment]
Its not using Rhino - MVCContrib uses Rhino under the hood - its a dependency on this I believe

Pau

**Comment by alastairs** [comment]
Ok.  In that case we need to be careful about introducing this dependency and/or standardise around RhinoMocks instead of Moq. Including two mocking frameworks in the repo is going to cause confusion quickly.

**Comment by stack72** [comment]
Just removed the ref to Rhino Mocks and its still working - I will also swap in Moq instead of NSub (my very simple substitution framework of choice) but that will come later when all tests are added

**Comment by stack72** [comment]
Not going to be merged until this can be fixed to use Moq

**Pull request closed without merging**
